# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [1]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
marketing = pd.read_csv(url)

In [7]:
marketing.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='str')

In [12]:
# New df: low total_claim_amount (< 1000) & (response = "Yes" to last marketing campaign)
mask = (marketing["Total Claim Amount"] < 1000) & (marketing["Response"] == "Yes")
low_claim_yes = marketing[mask]

low_claim_yes

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [ ]:
# Avg monthly_premium & customer lifetime value by policy_type & gender for customer = "Yes"
yes_customers = marketing[marketing["Response"] == "Yes"]

pivot_yes = pd.pivot_table(
    yes_customers,
    values=["Monthly Premium Auto", "Customer Lifetime Value", "Total Claim Amount"],
    index="Policy Type",
    columns="Gender",
    aggfunc="mean",
).round(2)

pivot_yes

# Conclusions:
# The average Customer Lifetime Value (CLV) varies by both policy type and gender.
# For Corporate Auto, males have a higher average CLV than females (7944.47 vs. 7712.63).
# For Personal Auto, females have a higher average CLV than males (8339.79 vs. 7448.38).
# For Special Auto, males have a higher average CLV than females (8247.09 vs. 7691.58).

               Customer Lifetime Value          Monthly Premium Auto         \
Gender                               F        M                    F      M
Policy Type
Corporate Auto                 7712.63  7944.47                94.30  92.19
Personal Auto                  8339.79  7448.38                99.00  91.09
Special Auto                   7691.58  8247.09                92.31  86.34

               Total Claim Amount
Gender                          F       M
Policy Type
Corporate Auto             433.74  408.58
Personal Auto              452.97  457.01
Special Auto               453.28  429.53

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [ ]:
states_over_500 = marketing["State"].value_counts().reset_index()

states_over_500.columns = ["State", "Customer Count"]

states_over_500 = states_over_500[states_over_500["Customer Count"] > 500]

states_over_500

        State  Customer Count
0  California            3552
1      Oregon            2909
2     Arizona            1937
3      Nevada             993
4  Washington             888

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [ ]:
clv_by_education_gender = (
    marketing.groupby(["Education", "Gender"])["Customer Lifetime Value"]
    .agg(["max", "min", "median"])
    .round(2)
)

clv_by_education_gender.sort_values(by="max", ascending=False)

# Conclusions:
# The highest maximum CLV is for males with High School or Below education (83325.38).
# The lowest maximum CLV is for males with a Doctor education (32677.34).
# Looking at the median CLV, males with High School or Below education have the highest median (6286.73), followed by males with College education (6005.85).

                                  max      min   median
Education            Gender
High School or Below M       83325.38  1940.98  6286.73
Bachelor             F       73225.96  1904.00  5640.51
                     M       67907.27  1898.01  5548.03
College              F       61850.19  1898.68  5623.61
                     M       61134.68  1918.12  6005.85
High School or Below F       55277.45  2144.92  6039.55
Master               F       51016.07  2417.78  5729.86
                     M       50568.26  2272.31  5579.10
Doctor               F       44856.11  2395.57  5332.46
                     M       32677.34  2267.60  5577.67

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here